name: Django Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests: 
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        